CREATE DATABASE DB_TIENDA_ONLINE;
USE DB_TIENDA_ONLINE;

/*Seguridad*/

CREATE TABLE CAT_ROLES(
  NID_ROL TINYINT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(100),
  CDESCRIPCION VARCHAR(255),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CNOMBRE)
);

CREATE TABLE CAT_PERMISOS(
  NID_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(100),
  CDESCRIPCION VARCHAR(255),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CNOMBRE)
);

/*Permisos y usuarios*/

CREATE TABLE CAT_PAISES(
  NID_PAIS INT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(100),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CNOMBRE)
);

CREATE TABLE CAT_CIUDADES(
  NID_CIUDAD INT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(100),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CNOMBRE)
);

CREATE TABLE CAT_DELEGACION(
  NID_DELEGACION INT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(100),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CNOMBRE)
);

CREATE TABLE CAT_CODIGO_POSTAL(
  NID_CP INT AUTO_INCREMENT PRIMARY KEY,
  CCODIGO_POSTAL VARCHAR(10),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CCODIGO_POSTAL)
);

CREATE TABLE TBL_PAIS_CIUDAD(
  NID_PAIS INT NOT NULL,
  NID_CIUDAD INT NOT NULL,
  PRIMARY KEY (NID_PAIS, NID_CIUDAD),
  FOREIGN KEY (NID_PAIS) REFERENCES CAT_PAISES(NID_PAIS),
  FOREIGN KEY (NID_CIUDAD) REFERENCES CAT_CIUDADES(NID_CIUDAD)
);

CREATE TABLE TBL_CIUDAD_DELEGACION(
  NID_CIUDAD INT NOT NULL,
  NID_DELEGACION INT NOT NULL,
  PRIMARY KEY (NID_CIUDAD, NID_DELEGACION),
  FOREIGN KEY (NID_CIUDAD) REFERENCES CAT_CIUDADES(NID_CIUDAD),
  FOREIGN KEY (NID_DELEGACION) REFERENCES CAT_DELEGACION(NID_DELEGACION)
);

CREATE TABLE TBL_DELEGACION_CP(
  NID_DELEGACION INT NOT NULL,
  NID_CP INT NOT NULL,
  PRIMARY KEY (NID_DELEGACION, NID_CP),
  FOREIGN KEY (NID_DELEGACION) REFERENCES CAT_DELEGACION(NID_DELEGACION),
  FOREIGN KEY (NID_CP) REFERENCES CAT_CODIGO_POSTAL(NID_CP)
);

CREATE TABLE TBL_DIRECCION(
  NID_DIRECCION INT AUTO_INCREMENT PRIMARY KEY,
  NID_CP INT,
  NID_CIUDAD INT, 
  NID_PAIS INT,
  NID_DELEGACION INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  FOREIGN KEY (NID_CP) REFERENCES CAT_CODIGO_POSTAL(NID_CP),
  FOREIGN KEY (NID_CIUDAD) REFERENCES CAT_CIUDADES(NID_CIUDAD),
  FOREIGN KEY (NID_PAIS) REFERENCES CAT_PAISES(NID_PAIS),
  FOREIGN KEY (NID_DELEGACION) REFERENCES CAT_DELEGACION(NID_DELEGACION)
);

CREATE TABLE CAT_GENEROS(
	NID_GENERO TINYINT AUTO_INCREMENT PRIMARY KEY,
    CGENERO VARCHAR(20),
	BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
	DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DFECHA_BAJA DATETIME
);

CREATE TABLE TBL_PERSONAS(
  NID_PERSONA INT AUTO_INCREMENT PRIMARY KEY,
  NID_DIRECCION INT,
  NID_GENERO TINYINT NOT NULL,
  CNOMBRE VARCHAR(100),
  CAPELLIDO_PATERNO VARCHAR(100),
  CAPELLIDO_MATERNO VARCHAR(100),
  CCORREO VARCHAR(150),
  CTELEFONO VARCHAR(20),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CCORREO),
  FOREIGN KEY (NID_DIRECCION) REFERENCES TBL_DIRECCION(NID_DIRECCION)
);

CREATE TABLE TBL_USUARIOS(
  NID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
  NID_PERSONA INT,
  CUSUARIO VARCHAR(100),
  CPASSWORD VARCHAR(255),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CUSUARIO),
  FOREIGN KEY (NID_PERSONA) REFERENCES TBL_PERSONAS(NID_PERSONA)
);

/*Permisos y usuarios*/
CREATE TABLE TBL_USUARIOS_ROLES(
  NID_USUARIO_ROL INT AUTO_INCREMENT PRIMARY KEY,
  NID_USUARIO INT,
  NID_ROL TINYINT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_USUARIO, NID_ROL),
  FOREIGN KEY (NID_USUARIO) REFERENCES TBL_USUARIOS(NID_USUARIO),
  FOREIGN KEY (NID_ROL) REFERENCES CAT_ROLES(NID_ROL)
);

CREATE TABLE TBL_ROLES_PERMISOS(
  NID_ROL_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
  NID_ROL TINYINT NOT NULL,
  NID_PERMISO INT NOT NULL,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_ROL, NID_PERMISO),
  FOREIGN KEY (NID_ROL) REFERENCES CAT_ROLES(NID_ROL),
  FOREIGN KEY (NID_PERMISO) REFERENCES CAT_PERMISOS(NID_PERMISO)
);

/*Clientes*/
CREATE TABLE TBL_CLIENTES(
  NID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
  NID_PERSONA INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_PERSONA),
  FOREIGN KEY (NID_PERSONA) REFERENCES TBL_PERSONAS(NID_PERSONA)
);

/*Dirección*/

/*Productos*/
CREATE TABLE CAT_CATEGORIAS(
  NID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(100),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CNOMBRE)
);

CREATE TABLE TBL_SUBCATEGORIAS(
  NID_SUBCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
  NID_CATEGORIA INT,
  CNOMBRE VARCHAR(100),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_CATEGORIA, CNOMBRE),
  FOREIGN KEY (NID_CATEGORIA) REFERENCES CAT_CATEGORIAS(NID_CATEGORIA)
);

/*Proveedores*/
CREATE TABLE CAT_PROVEEDORES(
  NID_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(150),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CNOMBRE)
);

CREATE TABLE TBL_PRODUCTOS(
  NID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(200),
  CDESCRIPCION TEXT,
  MPRECIO DECIMAL(10,2),
  NID_SUBCATEGORIA INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_SUBCATEGORIA, CNOMBRE),
  FOREIGN KEY (NID_SUBCATEGORIA) REFERENCES TBL_SUBCATEGORIAS(NID_SUBCATEGORIA)
);

CREATE TABLE TBL_PROVEEDORES_PRODUCTOS(
  NID_PROVEEDOR_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
  NID_PROVEEDOR INT,
  NID_PRODUCTO INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_PROVEEDOR, NID_PRODUCTO),
  FOREIGN KEY (NID_PROVEEDOR) REFERENCES CAT_PROVEEDORES(NID_PROVEEDOR),
  FOREIGN KEY (NID_PRODUCTO) REFERENCES TBL_PRODUCTOS(NID_PRODUCTO)
);

/*Productos*/

/*Almacen e Inventario*/
CREATE TABLE TBL_ALMACEN(
  NID_ALMACEN INT AUTO_INCREMENT PRIMARY KEY,
  CNOMBRE VARCHAR(100),
  NID_DIRECCION INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (CNOMBRE),
  FOREIGN KEY (NID_DIRECCION) REFERENCES TBL_DIRECCION(NID_DIRECCION)
);

CREATE TABLE TBL_INVENTARIO(
  NID_INVENTARIO INT AUTO_INCREMENT PRIMARY KEY,
  NID_PRODUCTO INT,
  NID_ALMACEN INT,
  NSTOCK INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_PRODUCTO, NID_ALMACEN),
  FOREIGN KEY (NID_PRODUCTO) REFERENCES TBL_PRODUCTOS(NID_PRODUCTO),
  FOREIGN KEY (NID_ALMACEN) REFERENCES TBL_ALMACEN(NID_ALMACEN)
);

/*Ordenes*/
CREATE TABLE TBL_ORDENES(
  NID_ORDEN INT AUTO_INCREMENT PRIMARY KEY,
  NID_CLIENTE INT,
  MMONTO DECIMAL(12,2),
  DFECHA_ORDEN DATETIME,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  FOREIGN KEY (NID_CLIENTE) REFERENCES TBL_CLIENTES(NID_CLIENTE)
);

CREATE TABLE TBL_ORDEN_PRODUCTO(
  NID_ORDEN_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
  NID_ORDEN INT,
  NID_PRODUCTO INT,
  NCANTIDAD INT,
  MPRECIO DECIMAL(10,2),
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_ORDEN, NID_PRODUCTO),
  FOREIGN KEY (NID_ORDEN) REFERENCES TBL_ORDENES(NID_ORDEN),
  FOREIGN KEY (NID_PRODUCTO) REFERENCES TBL_PRODUCTOS(NID_PRODUCTO)
);

/*Envios y repartidores*/
CREATE TABLE TBL_REPARTIDORES(
  NID_REPARTIDOR INT AUTO_INCREMENT PRIMARY KEY,
  NID_PERSONA INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_PERSONA),
  FOREIGN KEY (NID_PERSONA) REFERENCES TBL_PERSONAS(NID_PERSONA)
);

CREATE TABLE TBL_ENVIOS(
  NID_ENVIO INT AUTO_INCREMENT PRIMARY KEY,
  NID_ORDEN INT,
  NID_REPARTIDOR INT,
  DFECHA_ENVIO DATETIME,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_ORDEN),
  FOREIGN KEY (NID_ORDEN) REFERENCES TBL_ORDENES(NID_ORDEN),
  FOREIGN KEY (NID_REPARTIDOR) REFERENCES TBL_REPARTIDORES(NID_REPARTIDOR)
);

/*Interacción*/
CREATE TABLE TBL_COMENTARIOS(
  NID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY,
  NID_CLIENTE INT,
  NID_PRODUCTO INT,
  CTEXTO TEXT,
  NVALORACION INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  FOREIGN KEY (NID_CLIENTE) REFERENCES TBL_CLIENTES(NID_CLIENTE),
  FOREIGN KEY (NID_PRODUCTO) REFERENCES TBL_PRODUCTOS(NID_PRODUCTO)
);

CREATE TABLE TBL_LISTA_DESEOS(
  NID_LISTA INT AUTO_INCREMENT PRIMARY KEY,
  NID_CLIENTE INT,
  NID_PRODUCTO INT,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  UNIQUE (NID_CLIENTE, NID_PRODUCTO),
  FOREIGN KEY (NID_CLIENTE) REFERENCES TBL_CLIENTES(NID_CLIENTE),
  FOREIGN KEY (NID_PRODUCTO) REFERENCES TBL_PRODUCTOS(NID_PRODUCTO)
);

CREATE TABLE CAT_ESTATUS(
  NID_ESTATUS TINYINT AUTO_INCREMENT PRIMARY KEY, 
  CESTATUS VARCHAR(50) NOT NULL,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME
);

CREATE TABLE TBL_ORDENES_ESTATUS(
  NID_ORDEN_ESTATUS INT AUTO_INCREMENT PRIMARY KEY,
  NID_ESTATUS TINYINT NOT NULL,
  NID_ORDEN INT NOT NULL,
  BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
  DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DFECHA_BAJA DATETIME,
  FOREIGN KEY (NID_ESTATUS) REFERENCES CAT_ESTATUS(NID_ESTATUS),
  FOREIGN KEY (NID_ORDEN) REFERENCES TBL_ORDENES(NID_ORDEN)
);

CREATE TABLE TBL_ERRORES_BASE(
	NID_ERROR INT AUTO_INCREMENT PRIMARY KEY,
	CMENSAJE_ERROR VARCHAR(100),
    NNUMERO_LINEA SMALLINT,
	BHABILITADO BOOLEAN NOT NULL DEFAULT TRUE,
	DFECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DFECHA_BAJA DATETIME
);
