spring.application.name=online
spring.datasource.url=jdbc:mysql://localhost:3308/DB_TIENDA_ONLINE
spring.datasource.username=Luis
spring.datasource.password=DesarrollandoApis
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.mongodb.uri=mongodb://localhost:27017/DB_TIENDA_ONLINE