-- schema.sql
CREATE DATABASE IF NOT EXISTS db_reconstruye;
USE db_reconstruye;

CREATE TABLE tbl_personas (
    NID_PERSONA INT AUTO_INCREMENT PRIMARY KEY,
    NID_GENERO INT,
    NID_DIRECCION INT,
    CNOMBRE VARCHAR(200) NOT NULL,
    CPRIMER_APELLIDO VARCHAR(200) NOT NULL,
    CSEGUNDO_APELLIDO VARCHAR(200) NOT NULL,
    CNUMERO_TELEFONO VARCHAR(15) NOT NULL,
    CNUMERO_TELEFONO_ALTERNATIVO VARCHAR(15),
    CCORREO_ELECTRONICO VARCHAR(50) NOT NULL,
    DFECHA_NACIMIENTO DATETIME,
    BHABILITADO TINYINT(1) NOT NULL,
    DFECHA_ALTA DATETIME NOT NULL,
    DFECHA_BAJA DATETIME
);